- name: Demo on conditions
  hosts: localhost
  connection: local
  tasks:
    - name: Printing Hello universe
      ansible.builtin.debug:
        msg: Hello universe1
      when: role=="devops"

    - name: Printing India
      ansible.builtin.debug:
          msg: my India
      when: role=="ansible"