- name: Loops concept
  hosts: localhost
  connection: local
  tasks: 
    - name: Loops Printing  
      ansible.builtin.debug:
        msg: cars are - {{item}}
      loop:
        - bmw
        - scooda
        - audi
    
    - name: Fruits with Quantity
      ansible.builtin.debug:
        msg: Furits are - {{item.name}} Quantity is -{{item.Quantity}}
      loop:
        - {name: Apple, Quantity: 100}
        - {name: Orange, Quantity: 200}
        - {name: Goa, Quantity: 300}
        - {name: Grape, Quantity: 400}