- name: Loops concept
  hosts: localhost
  connection: local
  tasks: 
    - name: Loops Printing  
      ansible.builtin.debug:
        msg: cars are - {{item}}
      loop:
        - bmw
        - scooda
        - audi