- name: Encrypted Text
  hosts: localhost
  tasks:  
    - name: Read the file Content
      ansible.builtin.shell: cat Sample.txt
      register: file_content

    - name: Encrypting the file data
      set_fact:
       encryptedContent: "{{file_content.stdout | password_hash('bcrypt','subbu') }}"

    - name: Save the Encrypted file
      ansible.builtin.copy:
        source: "{{encryptedContent}}"
        dest: encryptedContent.txt  
